# Generated by Django 2.2.7 on 2019-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyality_score', models.IntegerField(default=1)),
                ('loyality_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_comp_score', models.IntegerField(default=1)),
                ('part_comp_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_knowledge_score', models.IntegerField(default=1)),
                ('prod_knowledge_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_comm_score', models.IntegerField(default=1)),
                ('prof_comm_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relations_score', models.IntegerField(default=1)),
                ('relations_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_score', models.IntegerField(default=1)),
                ('Strategy_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teamwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamwork_score', models.IntegerField(default=1)),
                ('teamwork_status', models.IntegerField(default=1)),
            ],
        ),
    ]
